# Generated by Django 3.1.7 on 2021-07-05 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='age',
            field=models.IntegerField(default=5),
        ),
        migrations.DeleteModel(
            name='Result',
        ),
    ]
